=== SeverinBuchser/GitAnalyzer/src/main/resources/schemas/config.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "config",
  "title": "Config",
  "description": "A config for the GitAnalyzer project.",
  "type": "object",
  "properties": {
    "clone": {
      "description": "Clones the projects of the lists of projects.",
      "type": "boolean",
      "default": true
    },
    "analyze": {
      "description": "Analyzes the projects of the lists of projects.",
      "type": "boolean",
      "default": true
    },
    "projectLists": {
      "$ref": "projectLists.json"
    },
    "out": {
      "description": "The directory of the output files.",
      "type": "string",
      "default": ""
    },
    "verbose": {
      "description": "Verbose mode. Additional helpful information will be displayed. Verbose mode only has an effect on the analysis.",
      "type": "boolean",
      "default": false
    }
  },
  "additionalProperties": false
}

=== SeverinBuchser/GitAnalyzer/configs/config.test.json
{
    "analyze": true,
    "clone": true,
    "projectLists": [
        {
            "skip": false,
            "list": "../project-lists/test-one.csv",
            "dir": "../../ba_project-dirs/test-one",
            "suffix": ""
        },
        {
            "skip": false,
            "list": "../project-lists/test-two.csv",
            "dir": "../../ba_project-dirs/test-two",
            "suffix": ""
        }
    ],
    "out": "../out"
}

=== SeverinBuchser/GitAnalyzer/configs/gui.test.config.json
{
    "analyze": true,
    "clone": true,
    "projectLists": [
        {
            "list": "../project-lists/projects_name_asc-stars-10.csv",
            "dir": "../../ba_project-dirs/projects_name_asc-stars-10"
        },
        {
            "skip": false,
            "list": "../project-lists/test.csv",
            "dir": "",
            "suffix": ""
        }
    ],
    "out": "../out",
    "verbose": false
}
